### ISSUE TITLE
Use an array reference of strings for ENV vars when specifying `env_key`

### ISSUE THREAD

**Issue by vanHoesel** [mohawk2/moox-attribute-env#2]
For my use case, we historically used one env-var, but than the company that build the main parts of the software decided to change the names of there variables.

I want a solution that I can have a list of names that will be tried and uses the first existing/defined value:
```perl
# look for $ENV{attr_val1} and $ENV{ATTR_VAL1} first, followed by $ENV{attr_val2} and $ENV{ATTR_VAL2}
has attr => (
  is => 'ro',
  env_key => ['attr_val1', 'attr_val2'],
);
```

**Comment by mohawk2** [comment]
PRs most welcome!

**Comment by vanHoesel** [comment]
Cool, sounds like an approved feature request. Code will follow soon!

**Comment by mohawk2** [comment]
I'd say that when requesting a feature, if one is also offering to implement it, it's a good idea to say so ;-)

I look forward to seeing the code!

**Comment by vanHoesel** [comment]
I will try to get it done during $WORK hours this or next week, as it is not just for fun :-)
